---
title: "Lab 3.6"
author: "Anna Hovis"
date: "Thursday, February 12, 2015"
output: html_document
---
```{r}
knitr::opts_chunk$set(comment = NA, message = FALSE, warning = FALSE, fig.align = "center")
library(ISLR)
library(MASS)
```

#Simple Linear Regression

```{r}
lm.fit <- lm(medv ~ lstat, data = Boston)
summary(lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
predict(lm.fit, data.frame(lstat = (c(5, 10, 15))), interval = "confidence")
predict(lm.fit, data.frame(lstat = (c(5, 10, 15))), interval = "prediction")
```

#Base Graphs

```{r}
plot(medv ~ lstat, data = Boston, pch = 19, col = "pink")
abline(lm.fit, lwd = 3,col = "red")
par(mfrow = c(2, 2))
plot(lm.fit)
par(mfrow=c(1, 1))
par(mfrow=c(3, 1))
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
par(mfrow=c(1, 1))
```

#ggplot2 Graphs

```{r}
library(ggplot2)
ggplot(data = Boston, aes(x = lstat, y = medv)) +
  geom_point(color = "pink") +
  theme_bw() + 
  geom_smooth(method = "lm")
# 
ggplot(data = Boston, aes( x= lstat, y = medv)) +
  geom_point(color = "pink") +
  theme_bw() + 
  geom_smooth()
```

#Using fortify

```{r}
NDF <- fortify(lm.fit)
head(NDF)
ggplot(data = NDF, aes(x = .fitted, y = .resid)) + 
         geom_point() +
         theme_bw()
```

#Multiple Linear Regression

```{r}
lm.fit <- lm(medv ~ lstat + age, data = Boston)
summary(lm.fit)
lm.fit <- lm(medv ~ ., data = Boston)
summary(lm.fit)
library(car)
vif(lm.fit)
lm.fit1 <- lm(medv ~ . -age, data = Boston)
summary(lm.fit1)
lm.fit1 <- update(lm.fit, ~ . - age)
```

#Interaction Terms

```{r}
summary(lm(medv ~ lstat * age, data = Boston))
```

#Non-linear Transformations of the Predictors

```{r}
lm.fit2 <- lm(medv ~ lstat + I(lstat^2), data = Boston)
summary(lm.fit2)
lm.fit <- lm(medv ~ lstat, data = Boston)
anova(lm.fit, lm.fit2)
par(mfrow = c(2, 2))
plot(lm.fit2)
lm.fit5 <- lm(medv ~ poly(lstat, 5), data = Boston)
summary(lm.fit5)
summary(lm(medv ~ log(rm), data = Boston))
```

#Qualitative Predictors

```{r}
names(Carseats)
lm.fit <- lm(Sales ~ . + Income:Advertising + Price:Age, data = Carseats)
summary(lm.fit)
contrasts(Carseats$ShelveLoc)
```

#Writing Functions

```{r}
LoadLibraries=function(){
 library(ISLR)
 library(MASS)
 print("The libraries have been loaded.")
 }
LoadLibraries
LoadLibraries()
```